### ISSUE TITLE
doesn't work with foobar 1.4 beta 11

### ISSUE THREAD

**Issue by StephanBusch** [unjello/foo_input_amr#2]
Hello,

this plugin worked in earlier versions but doesn't accept / playback any .amr with foobar 1.4 beta 11.

**Comment by quangnh89** [comment]
I have tested foobar 2000 v1.4 beta 11. The plugin is loaded successfully.
![foobar2000_v1 4_beta_11](https://user-images.githubusercontent.com/10832563/38204539-8f2efda6-36cd-11e8-8391-d9d8f7d09bcf.PNG)

I can play AMR-NB by using foobar2000. You can test the plugin with some sample files from here (https://wiki.multimedia.cx/index.php/AMR-NB) 

I think your AMR files are Adaptive Multi-Rate **Wideband** (AMR-WB), first bytes are "#!AMR-WB". _foo_input_amr_ currently does not support this format. Can you upload some samples? I will use them to find the problem.

**Comment by StephanBusch** [comment]
I am using Call Recorder and some files do open and playback but some don't.
Here is an example: www.squeezechart.com/2018-03-08_11-04-31.amr

**Comment by unjello** [comment]
This is AMR-NB tho. It is quite interesting. It seems it plays some NB and not others. I'll look into this, please be patient :)

**Comment by unjello** [comment]
@StephanBusch immediate cause of an issue is the new API that started throwing exception in case of seeking behind a file. That in turn seems to be caused by a type of frame I haven't anticipated properly (it seems that your example contains payload with a phone number in it). I have done a quick fix to enable playback, and will make a proper fix later. Need to better understand the file format apparently :)
